question_data = [
    {"category": "Entertainment: Television",
     "type": "boolean",
     "difficulty": "medium",
     "question": "AMC's 'The Walking Dead' Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in "
                 "Season 1.", 
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The name of the main character of the video game 'The Legend of Zelda', is Zelda.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "French is an official language in Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In 'Mario Kart 64', Waluigi is a playable character.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Art",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Vincent van Gogh cut off one of his ears.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Type 1 diabetes is a result of the liver working improperly.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the films 'Wolf Children' "
                 "and 'The Boy and the Beast'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Peyton Manning retired after winning Super Bowl XLIX.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Sports", "type": "boolean", "difficulty": "medium",
                                      "question": "Tennis was once known as Racquetball.",
                                      "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Ottawa is the capital of Canada.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "According to Norse mythology, Loki is a mother.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In 'Team Fortress 2', the 'Bill&#039;s Hat' is a reference to the game 'Dota 2'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The color orange is named after the fruit.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
     "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the "
                 "distance from the Earth to the Sun.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "The Angry Video Game Nerd&#039;s alter ego is 'Board James'.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
                                       "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "question": "Sean Connery wasn&#039;t in 'Indiana Jones and the Kingdom of the Crystal Skull' because he found retirement too enjoyable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named 'Timmy' and 'Jimmy'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
     "question": "Switzerland has four national languages, English being one of them.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "E = MC3",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Brandon Routh plays the titular character in the movie 'John Wick'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Scatman John&#039;s real name was John Paul Larkin.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Portal, the Companion Cube&#039;s ARE sentient.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                       "question": "In Rugby League, performing a '40-20' is punished by a free kick for the opposing team.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "'Metal Gear Solid 3: Snake Eater' was released in 2004.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "'Return to Castle Wolfenstein' was the only game of the Wolfenstein series where you don&#039;t play as William 'B.J.' Blazkowicz.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Hidden in the files for 'Mario Kart Arcade GP' is a picture of the Beslan school hostage crisis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as  'the Zone'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Dave Grohl recorded the Foo Fighters&#039; debut, 'Foo Fighters,' by himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
     "question": "Tigers have one colour of skin despite the stripey fur.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "medium",
     "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "There are 2 player roles in Trouble in Terrorist Town.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
